services:
  telegram-morpho-bot:
    build: .
    ports:
      - '${PORT}:${PORT}'
    networks:
      - default
      - shared-net
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - BASE_URL=${BASE_URL}
      - WALLET_ADDRESS=${WALLET_ADDRESS}
      - CHAIN_ID=${CHAIN_ID}
      - TG_CHAT_ID=${TG_CHAT_ID}
      - PORT=${PORT}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - default

networks:
  shared-net:
    external: true
    name: billy-shared-network
